baseurl = "/"
languageCode = "en"
title = "Connor Gilroy"
theme = "kiss"
copyright = "&copy; <a href=\"mailto:cgilroy@uw.edu\">Connor Gilroy</a> 2018"
disqusShortname = ""
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params.assets]
customCSS = ["css/custom.css"]

[params.rss]

includeContent = true # Includes whole content in rss
authorName = "Connor Gilroy" # Site author's full name
authorEmail = "cgilroy@uw.edu"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "Connor Gilroy" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.sections_left]

# these are apparently in alphabetical order by url...
# how can I make them not be?
# in Yihui's example, the menu is ordered with a "weight" parameter...

  "/" = "Home"
  "/about/" = "About"
  "/research/" = "Research"
  "/teaching/" = "Teaching"
  "/cv/" = "CV"
  
# [params.sections_right]
#  "/blog/" = "Blog"
#  "/thing/" = "Another"

[[menu.sections_left]]
  name = "Home"
  url = "/"
  weight = 1

# maybe get rid of About page, or rename it Bio?
# [[menu.sections_left]]
#  name = "About" 
#  url = "/about/"
#  weight = 2
  
[[menu.sections_left]]
  name = "Research"
  url = "/research/"
  weight = 3
  
[[menu.sections_left]]
  name = "Teaching"
  url = "/teaching/"
  weight = 4

[[menu.sections_left]]
  name = "CV" 
  url = "/cv/"
  weight = 5
  
# [[menu.sections_left]]
#  name = "Blog"
#  url = "/post/"
#  weight = 6
    
[params.social]

twitter = "ccgilroy"
github = "ccgilroy"
email = "cgilroy@uw.edu"
linkedin = ""
facebook = ""
instagram = ""
codepen = ""

[params.social.config]
# platforms = ["github","facebook","twitter","instagram","email","codepen","linkedin"]
platforms = ["email", "twitter", "github"]

[params.matomoAnalytics]
# siteID = 1
# rootURL = "//matomo.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
